# Generated by Django 4.2.1 on 2023-05-13 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'Виконане'), ('processing', 'В процесі'), ('scheduled', 'Заплановане')], default='scheduled', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker_app.subject', verbose_name='subjects'),
        ),
    ]
